version: "3.9"

services:
  web:
    build: .
    image: kmnist-app
    ports:
      - "8000:8000"  # Usa la variable PORT o 8000 por defecto
    environment:
      - DJANGO_SETTINGS_MODULE=kmnist.settings
      - PORT=8000  # Asegúrate de pasar la variable PORT
